site_name: Crawl 3
site_description: 'Crawl 3 User guide and documentation'
site_author: 'Sam Duke'
site_url: 'https://samjohnduke.github.io/crawl3-docs/'

# Repository
repo_name: 'samjohnduke/crawl3-docs'
repo_url: 'https://github.com/samjohnduke/crawl3-docs'

# Copyright
copyright: 'Copyright &copy; 2018 Sam Duke'

pages: 
  - Home: index.md 
  - Getting Started: getting-started.md
  - About: 
    - Objective: about/about.md 
    - License: about/license.md

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'


# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
